# http://mgalgs.github.io/2013/05/10/hacking-your-ELF-for-fun-and-profit.html

all: section_hacking

section_hacking:
	gcc -g -O0 -Werror -Wall -o section_hacking section_hacking.c plugin.c

clean:
	rm -f *.o section_hacking

